version: 0.2

phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/ROOT.war
    - appspec.yml
  scripts
    --start.sh
    --setenv.sh
    --stop.sh
  discard-paths: yes
